- elements/answer-board/src/App.jsx
> [answer-board] Use new sdk structure

- .github/workflows/build-and-deploy.yml
- elements/reigns/babel.config.js
- elements/reigns/package-lock.json
- elements/reigns/package.json
- elements/reigns/src/features/game/gameSlice.test.ts
- elements/reigns/src/features/game/gameSlice.ts
https://mobitroll.atlassian.net/browse/FRES-1145
* Adds jest
* Adds limited test coverage
* Runs in workflow
> Add jest to reigns

- elements/reigns/public/games/dont-starve.json
- elements/reigns/public/games/gdpr.json
> 🐛 fix assetsUrl

- elements/reigns/public/games/dont-starve.json
- elements/reigns/public/games/gdpr.json
- elements/reigns/src/features/game/gameSlice.test.ts
- elements/reigns/src/features/game/gameSlice.ts
- elements/reigns/src/features/game/types.ts
- elements/reigns/src/features/game/validateGameDefinition.test.ts
- elements/reigns/src/features/game/validateGameDefinition.ts
https://mobitroll.atlassian.net/browse/FRES-1117
* Define `no_custom` and `yes_custom` in game definition
* Validate columns
* Apply flags to `GameState` on yes/no
> ✨ Set flags

- elements/reigns/src/features/game/gameSlice.test.ts
- elements/reigns/src/features/game/gameSlice.ts
- elements/reigns/src/features/game/selectNextCard.test.ts
- elements/reigns/src/features/game/selectNextCard.ts
- elements/reigns/src/features/game/types.ts
- elements/reigns/src/features/game/validateGameDefinition.test.ts
- elements/reigns/src/features/game/validateGameDefinition.ts
https://mobitroll.atlassian.net/browse/FRES-1118
* Use conditions to select next card
> ✨ Conditions

- elements/reigns/src/features/game/gameSlice.test.ts
- elements/reigns/src/features/game/gameSlice.ts
https://mobitroll.atlassian.net/browse/FRES-1160
> 🐛 fixes FRES-1160

- elements/reigns/src/App.tsx
- elements/reigns/src/useFresco.ts
pull out `useFresco` - required by upcoming PR
> ♻ extract useFresco

- inventory/index.json
https://mobitroll.atlassian.net/browse/FRES-1112
We need to know when the avatar leaves the voting zones so we can recalculate votes
> ✨ add leave events

- elements/reigns/package-lock.json
- elements/reigns/package.json
- elements/reigns/src/App.tsx
- elements/reigns/src/features/game/Game.test.ts
- elements/reigns/src/features/game/Game.ts
- elements/reigns/src/features/game/gameChangeListener.test.ts
- elements/reigns/src/features/game/gameChangeListener.ts
- elements/reigns/src/features/game/gameSlice.test.ts
- elements/reigns/src/features/game/gameSlice.ts
- elements/reigns/src/features/game/mocks.tsx
- elements/reigns/src/features/host/determineHost.test.ts
- elements/reigns/src/features/host/determineHost.ts
- elements/reigns/src/features/host/persistence.ts
- elements/reigns/src/features/voting/resolveRound.test.ts
- elements/reigns/src/features/voting/useCollateVotes.ts
- elements/reigns/src/features/voting/useOnFrescoStateUpdate.ts
- elements/reigns/src/index.tsx
- elements/reigns/src/store.ts
https://mobitroll.atlassian.net/browse/FRES-1217
> ✨ Reset game on url change

- elements/README.md
- elements/reigns/src/fresco.d.ts
https://mobitroll.atlassian.net/browse/FRES-1205
My intention would be to eventually extract `fresco.d.ts` (and `sdk.js` etc) into its own package.
> 📝 sdk docs

- elements/reigns/src/App.tsx
- elements/reigns/src/Game.tsx
- elements/reigns/src/features/host/usePersistIsMounted.ts
- elements/reigns/src/features/voting/useCollateVotes.ts
- elements/reigns/src/features/voting/useVoteListener.ts
- elements/reigns/src/useFresco.ts
https://mobitroll.atlassian.net/browse/FRES-1218
Waits until sdk is loaded before rendering any game stuff.
> 🐛 wait for sdk to load

- elements/reigns/package-lock.json
- elements/reigns/package.json
- elements/reigns/src/features/game/Game.ts
- elements/reigns/src/features/game/gameChangeListener.test.ts
- elements/reigns/src/features/game/gameChangeListener.ts
- elements/reigns/src/features/game/gameSlice.ts
- elements/reigns/src/features/game/parseCardsFromCsv.test.ts
- elements/reigns/src/features/game/parseCardsFromCsv.ts
- elements/reigns/src/features/game/selectAnswer.ts
- elements/reigns/src/features/game/selectNextCard.ts
- elements/reigns/src/features/game/types.ts
- elements/reigns/src/features/game/validateGameDefinition.ts
- elements/reigns/src/features/voting/useOnFrescoStateUpdate.ts
- elements/reigns/src/fresco.d.ts
- elements/reigns/src/useFresco.ts
https://mobitroll.atlassian.net/browse/FRES-1235
https://user-images.githubusercontent.com/6289998/172126719-ac12fa64-ef8e-4345-864c-440943f1c269.mp4
> ✨ card editor

- elements/timer/README.md
I added more instructions to make a better set up.
Give me your feedback 😁
> Edit Timer README with new instructions

- elements/reigns/package-lock.json
- elements/reigns/package.json
- elements/reigns/src/Question.tsx
- elements/reigns/src/style.css
This PR adds auto text fitting for the question card content 
It is based on top of https://github.com/fres-co/fresco-community/pull/57 but could be split if needed.
> Reigns - question auto fit

- elements/timer/index.htm
- elements/timer/index.js
Hello ! I finished the buttons styles of the Timer 👍
**This a screenshot of design for you have a support 😁**
> [Timer] Buttons style

- elements/reigns/src/features/game/Game.ts
- elements/reigns/src/features/game/mocks.tsx
this PR adds fresco event when a turn finished, so other fresco elements can update based on the card that was picked
> :sparkes: each turn answer should emit a fresco event

- elements/reigns/src/Meter.tsx
- elements/reigns/src/style.css
https://mobitroll.atlassian.net/browse/FRES-1402
> 💄 show meter labels

- elements/ticker/README.md
- elements/ticker/index.html
Easy repeating custom events in a fresco space
> ✨ add ticker extension

- elements/reigns/src/Meter.tsx
- elements/reigns/src/style.css
https://mobitroll.atlassian.net/browse/FRES-1512
> 💄 ellipsis on long stat name

- elements/reigns/src/App.tsx
https://mobitroll.atlassian.net/browse/FRES-1520
> 🐛 fix loading/error styles

- elements/reigns/src/AnswerArea.tsx
- elements/reigns/src/Question.tsx
- elements/reigns/src/style.css
- elements/reigns/src/useTextFit.test.ts
- elements/reigns/src/useTextFit.ts
https://mobitroll.atlassian.net/browse/FRES-1513
> Textfit answers

- elements/reigns/src/AnswerArea.tsx
- elements/reigns/src/Logger.ts
- elements/reigns/src/constants.ts
- elements/reigns/src/features/game/gameSlice.ts
- elements/reigns/src/features/host/determineHost.ts
- elements/reigns/src/features/host/hostSlice.ts
- elements/reigns/src/features/voting/animateRoundTransition.ts
- elements/reigns/src/features/voting/calculateAnswer.ts
- elements/reigns/src/features/voting/persistence.ts
- elements/reigns/src/features/voting/resolveRound.ts
- elements/reigns/src/features/voting/triggerEventOnParticipantVote.ts
- elements/reigns/src/features/voting/useOnFrescoStateUpdate.ts
- elements/reigns/src/features/voting/useRoundedRectangleProgress.tsx
- elements/reigns/src/features/voting/useVoteListener.ts
This PR fixes a bug with the story-quizz background fill animation
Join three players to reigns
Vote same answer with all three
Answer background fill does not appear until round is ended. Answer background fill is cleared when new round is starting.
Answer background fill appears at majority, is cleared with final vote.
> 🐛 fix background fill

- elements/reigns/public/games/dont-starve.csv
https://frescoapp.slack.com/archives/C01GLNXLKJS/p1658987545275339
> ✨ a more gamified dont-starve

- elements/reigns/src/Logger.ts
- elements/reigns/src/features/host/hostSlice.ts
- elements/reigns/src/features/voting/calculateAnswer.ts
- elements/reigns/src/features/voting/persistence.test.ts
- elements/reigns/src/features/voting/resolveRound.test.ts
- elements/reigns/src/features/voting/resolveRound.ts
https://mobitroll.atlassian.net/browse/FRES-1529
1. Join three people to game
1. Two people vote (Countdown starts)
1. Remove one vote
Countdown stops, one vote removed
Countdown stops, both votes removed
> 🐛 fix votes removed in multi-player

- elements/reigns/src/App.tsx
- elements/reigns/src/Game.tsx
- elements/reigns/src/Meter.tsx
- elements/reigns/src/screens/EndedScreen/EndedScreen.tsx
- elements/reigns/src/screens/NotStartedScreen.tsx
- elements/reigns/src/screens/StartedScreen.tsx
- elements/reigns/src/style.css
This PR is another attempt of highlighting the user stats that trigger the game to fail.
it's a rework of https://github.com/fres-co/fresco-community/pull/117
https://user-images.githubusercontent.com/1194083/183644022-45688c38-1f47-4e2a-8f2a-3c5624d3201e.mov
> Death stat animation glow

- inventory/index.json
Sets vote on/off volume to 20%
> 💄 set vote volume to 20%

- elements/reigns/src/style.css
👆 [FRES-1689](https://mobitroll.atlassian.net/browse/FRES-1689)
> 💄 remove color from static meter

- elements/reigns/jest.config.js
- elements/reigns/src/Game.test.tsx
- elements/reigns/src/Header.test.tsx
- elements/reigns/src/Header.tsx
- elements/reigns/src/features/game/Game.test.ts
- elements/reigns/src/features/game/Game.ts
- elements/reigns/src/features/game/selectNextCard.ts
- elements/reigns/src/features/game/selectors.ts
- elements/reigns/src/jest.setup.ts
- elements/reigns/src/style.css
https://mobitroll.atlassian.net/browse/FRES-1687
> ✨use show_resources flag to toggle resource display

- elements/reigns/src/Game.test.tsx
- elements/reigns/src/Game.tsx
- elements/reigns/src/RoundLabel.tsx
- elements/reigns/src/screens/VotingScreen.tsx
this PR fixes the visible value for round valiue when game is ended and finished.
> :bug: fix visible round value when finished game

- .github/workflows/build-and-deploy.yml
this PR setup a new build phase for kahoot controller when merging on master
> 🔧  deploy kahoot controller

- elements/timer/index.css
- elements/timer/index.htm
- elements/timer/index.js
> Simplifies and improve the timer styles

- elements/answer-board/src/App.jsx
- elements/answer-board/src/style.css
> Restyle answer board

- .github/workflows/build-and-deploy.yml
[JIRA](https://mobitroll.atlassian.net/browse/FRES-2344?atlOrigin=eyJpIjoiYTFiOGVjNGEzOGRhNDZjOTgzY2Q2MGFmMDI3YTQzZmIiLCJwIjoiaiJ9)
> Commenting out the build for Reigns as it is broken.

- elements/kahoot-controller/src/App.tsx
- elements/kahoot-controller/src/index.css
Hi,
this PR adds a new confirmation screen before reset the pin.
This is to reduce change people inadvertly reset pin and disturb a whole conference
> :sparkles: confirmation before reset pin

- elements/carousel/README.md
- elements/carousel/index.htm
- elements/carousel/index.js
this PR adds a new elements, inspired by the card desk, but allow to display image instead of text.
this could be useful to pick random item in the list, such as dices, or communicate instructions with visual signals
> :sparkles: add new elements to display list of image

- elements/kahoot-controller/src/App.tsx
- elements/kahoot-controller/src/screens/KahootPlayer.tsx
- Allows to change controller url via query string parameter. 
- Passes nickname too.
Related PRs:
- https://github.com/fres-co/fresco/pull/1943
- https://github.com/fres-co/fresco-realtime/pull/101
> Kahoot controller changes
