fres-co/fresco-community

- elements/README.md
- elements/timer/index.htm
- elements/timer/index.js
this PR allows only participants with edit permission to trigger the timer.
it can not be merged as it, since it requires a new addition to the SDK, (exposing permissions)
> :sparkles: disable timer for non editor

- elements/reigns/src/App.tsx
- elements/reigns/src/fresco.d.ts
Inside the `Reigns` like game, after each vote, we want to give the possibility to reset the user position to a neutral zone.
this PR implements this.
it use the extension name to prefix the new destination zone name, which should be like `<name>-neutral`
> :sparkles: give the possibility to teleport to a new zone after each vote

- elements/reigns/src/style.css
Stops user selection of text within the extension, and thereby the cursor from changing to a caret.
> ✨ Stop cursor changing

- inventory/index.json
this PR updates the inventory elements of the reign mechanism to have a double click to move working on top of answer zones.
> :sparkles: double click to move on voting area

- elements/reigns/src/Meter.tsx
- elements/reigns/src/Meters.tsx
- elements/reigns/src/features/game/Game.test.ts
- elements/reigns/src/features/game/objectMother.ts
- elements/reigns/src/features/game/types.ts
- elements/reigns/src/style.css
this PR implements a tooltip visible when hovering a ressource icon, showing its name.
> Feature/fres 1221/show ressource name hover

- elements/reigns/src/features/host/hostSlice.ts
This reverts commit 11eec225fd1cc9b2bf4e823c6c250cd8781ffff4.
having the log to know who is the host is considered for now to be useful for debug purpose
> Revert "remove debug log"

- inventory/index.json
This PR update the Reigns inventory item to submit the vote only when the player stops into the voting zone, instead of when it entered it.
this give more time for reflexion
> :triangular_flag_on_post: change vote submission when stopping into zone

- elements/reigns/src/style.css
Hi,
currenlty when pasting `extension://fres-co.github.io/fresco-community/elements/reigns/dist/` inside a fres.co space,
we are unable to start a game.
the issue is because the default size of the extension does not give enough space for the text to fit.
Then the height of the HtmlDivElement we ar proving the textfit is 0, which lead to a crash.
This PR reduces the size of the resources in case the extension is too small, to give more room to the text
> :bug: :liptstick: fix game layout for default extension integration

- elements/reigns/src/constants.ts
- elements/reigns/src/features/game/selectNextCard.test.ts
- elements/reigns/src/features/game/selectNextCard.ts
This PR implements a new feature,
where cards with of weight of `100` will be always picked over other cards.
> :sparkles: implement an infinit cards weight to discard other cards

- elements/reigns/src/features/game/Game.ts
- elements/reigns/src/features/game/gameSlice.ts
- elements/reigns/src/features/game/selectAnswer.ts
- elements/reigns/src/features/game/selectNextCard.test.ts
- elements/reigns/src/features/game/selectNextCard.ts
- elements/reigns/src/features/game/types.ts
- elements/reigns/src/features/voting/useOnFrescoStateUpdate.ts
https://mobitroll.atlassian.net/browse/FRES-1363
Reduces realtime packet size by switching `previouslySelectedCards: Card[]` to `previouslySelectedCardIds: string[]`.
Additional optimisations could be considered later:
- removing custom ids and switching from `id: string` to `id: number`
- switching `selectedCard: Card` to `selectedCardId: string`
> ✨ persist previous card ids only

- elements/README.md
- elements/reigns/src/fresco.d.ts
this PR adds the doc for the new triggerEvent function accessible through fresco SDK.
marking as draft as the `triggerEvent` function ins not yet available
> :memo: add new sdk triggerEvent function doc

- elements/reigns/src/features/game/Game.ts
- elements/reigns/src/features/game/gameSlice.ts
- elements/reigns/src/features/game/parseCardsFromCsv.ts
- elements/reigns/src/features/game/parseGameFromCsv.test.ts
- elements/reigns/src/features/game/parseGameFromCsv.ts
Hi,
this PR allows using a single CSV file for a full game definition.
here is a sample of a csv file that can be loaded https://docs.google.com/spreadsheets/d/e/2PACX-1vRHeFFu_3HnSy5L_xcWeq-1cAdTLRiOuGD83EEbdiw6UFcIvJWiXLMA0l08O6L-rRC3W0Ur8qBbewb2/pub?output=csv
Here is the public Google spreadsheet file used as a backend.
https://docs.google.com/spreadsheets/d/17HXDBv5ZdLGw8R-Tf1Rf1PeyRQlt5PBmDXPFwa6DnDE/edit#gid=127106150
the idea is to help create a new game without ever touching JSON.
> :sparkles: allow to load a full csv definition

- elements/reigns/src/MeterArrow.tsx
- elements/reigns/src/style.css
this PR updates the symbol used for the arrow resources of the story-quizz element.
this now looks more like an arrow,
> :lipstick: use real arrow symbol for ressource impact

- elements/timer/index.css
this Pr fixes the fact that the timer input is not correct on safari.
this is due to the fact that safari does not vertically center the input content, when specifying an `height` on it
> :liptsick: fix safari timer input visibility

- elements/reigns/sdk.js
- elements/reigns/src/AnswerArea.tsx
- elements/reigns/src/fresco.d.ts
- elements/reigns/src/mockSdkVote.tsx
This is a follow up from https://github.com/fres-co/fresco-community/pull/94 which implements some items that `elements/reigns` needs. There's a couple of issues with it, but it mostly works.
features:
* loads game
* local player can start game
* local player can play game
* all realtime data cached in `localStorage`, so supports refresh
* appears to support HMD better than embedded version
issues:
* had to add game-specific support (see mockSdkVote)
* transitions supported poorly, progress animation is still occurring _after_ round completion
> ✨ mock sdk

- inventory/index.json
Adds a conversation zone to `elements/reigns` template so dynamic conversations do not appear within the extension.
> ✨ add conversation zone

- elements/reigns/src/Meter.tsx
- elements/reigns/src/style.css
Adds an animation to depleted stats on the death screen.
This is a PR into `feature/FRES-1288-death-screen-with-stats`
https://user-images.githubusercontent.com/6289998/183556066-c0303f30-af63-4218-bae4-e33e5536cee1.mp4
> Depleted stat animation

- elements/reigns/src/Game.tsx
this PR fixes the fact that the card is not filled after a countdown is finish.
this is because the progress was never set to 1.
this PR override the progress props provided to the component when an answer is selected by countdown
> :bug: selected card should fill after countdown

- elements/timer/index.css
- elements/timer/index.js
This Pr fix an issue with the timer, when integrated inside a fresco space.
When the duration is edited, we update the element at every change, which retriggers the rendering of the whole component.
that PR changes that.
I also hide the start button when editing a field, because of a similar bug: when clicking on the button while editing a field, we do trigger the onChange handler, and then not the start, requiring a double click on the start button.
If we have more bugs or plan to create new feature inside this timer, it might be useful to consider switching to (p)react
> :liptisck: hidden start button while editing

- elements/kahoot-controller/vite.config.ts
Currently, loading Kahoot! controller extension with `extension://fres-co.github.io/fresco-community/elements/kahoot-controller/dist/` does not work because it tries to load assets from the same folder.
this PR copy the config from Reign folder to load config from the same base directory as index.html file
> :wrench: base config for hosting

- elements/kahoot-controller/src/App.tsx
this Pr solves the fact that the Kahoot! controller extension is not waiting for the fresco SDK to be ready before calling onStateChanged
> :bug: kahoot sdk not ready

- .github/workflows/build-and-deploy.yml
- .github/workflows/pr.yml
Hi,
this PR try to fix the Reigns build, by force node to version 16.
I noticed it was broken when using node 18
> :rotating_light: try to fix ci by forcing node version

- elements/answer-board/src/App.jsx
Hi,
I recently noticed that depending of the background color, the empty text might be unreadable.
this PR improves it by automatically switching the text color based on the background color.
https://user-images.githubusercontent.com/1194083/221656214-d4f356f7-3057-4887-9c1d-0ea67c3d45cd.mov
> :lipstick: automatic empty title color computation

- elements/kahoot-controller/src/index.css
this PR removes the default color of the kahoot controller background, so it can match any background.
The color was originally set before the phone container
> :liptsick: no background leaking of phone container

- elements/qrcode/README.md
- elements/qrcode/index.htm
- elements/qrcode/index.js
This PR adds a new elements that can be used to display a text/url encoded as qrcode.
it can be added int he space using extension://dev-community.fres.co/elements/qrcode/index.htm 
it uses https://github.com/soldair/node-qrcode with default options to create the code
> :sparkles: add a new qrcode element

- inventory/index.json
this PR fixes the fact that dev URL is currently provided as source of element for carousel.
> :bug: fix public carousel use in inventory
